### ISSUE TITLE
Banner for social sharing meta tag shows the GDG DevFest Ukraine 2016 image

### ISSUE THREAD

**Issue by rac2030** [gdgzh/devfest18-website#7]
Banner for social sharing meta tag shows the GDG DevFest Ukraine 2016 image when sharing the link on social media.
I shared it privately on Slack and it directly displayed the Ukraine banner.

**Comment by rac2030** [comment]
Its the file https://github.com/gdgzh/devfest18-website/blob/develop/images/social-share.jpg

**Comment by rac2030** [comment]
I don't know ;-)
They used 1 image for all but I googled and found following:
https://www.rakacreative.com/blog/social-media/social-media-image-sizes-always-up-to-date/

The code allows for different images for G+, Facebook and Twitter

**Comment by Aadjou** [comment]
that is super helpful, thanks.

**Comment by rac2030** [comment]
http://w3cinc.com/resources/social-media-image-sizes/
Another guide which seems to be comprehensive

**Comment by ChristofBuechi** [comment]
As discussed long time ago, this issue is solved
